version: "3.8"

services:
  spacy-api:
    image: spacy-server:latest
    restart: always
    networks:
      - spacy-network
    volumes:
      - .:/app
    deploy:
      replicas: 12
      resources:
        limits:
            cpus: "4"
            memory: "1G"
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - spacy-api
    restart: always
    networks:
      - spacy-network

networks:
  spacy-network:
